### PR TITLE
Prevent slots being overwritten by inner scope

### PR DESCRIPTION
**Pull request by rasmuswinter**
The compiled `ComponentNode` code can overwrite the `$slots` variable with nested components. This PR saves and restores the `$slots` variable

Note this also reduces the minimum php version to 7.2

### CODE REVIEW

**Comment by giorgiopogliani** [comment]
Nice! Thanks @rasmuswinter! Would you like to add a small test for this?

**Comment by giorgiopogliani** [comment]
Or if you can comment an example that cause the problem I will do the test later.

**Comment by rasmuswinter** [comment]
I'll try knocking together a test now. Thanks for the speedy response

**Comment by rasmuswinter** [comment]
@giorgiopogliani sorry for the delay. Here's a test that demonstrates the bug

**Comment by giorgiopogliani** [comment]
Awesome! Thanks!

**Pull request merged**
